id: PDEEDFC49
initial_creation_type: ocr
source_metadata:
  volumes:
    23cadb63682549f4aae8021025da912e:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
